### ISSUE TITLE
boolean not queries

### ISSUE THREAD

**Issue by kimsashenka** [Stratio/stratio-cassandra#10]
Boolean queries contaning only not clause works incorrectly
sample program

package arta.synergy.common.docs;
    
    import com.datastax.driver.core.*;
    
    import java.net.InetSocketAddress;
    import java.util.ArrayList;
    import java.util.Collections;
    
    /**
     * Created by exile
     * Date: 27.11.14
     * Time: 10:36
     */
    public class CassandraNotTest {
        public static void main(String[] args) {
            final CassandraNotTest ct = new CassandraNotTest();
            Session session = null;
            try {
    
                ct.connect("127.0.0.1");
                session = ct.getSession();
                session.execute("drop table testsort");
    
                session.execute("CREATE TABLE IF NOT EXISTS testsort(id int, counter1 int, value1 text, counter2 bigint , value2 text, counter3 int, value3 text, startdate timestamp, lucene text, " +
                        " PRIMARY KEY(id, counter1, value1, counter2)) WITH CLUSTERING ORDER BY (counter1 asc, value1 asc, counter2 asc) ");
                System.out.println("table created");
    
                session.execute("CREATE CUSTOM INDEX  IF NOT EXISTS testsort_lucene ON testsort (lucene) " +
                        " USING 'org.apache.cassandra.db.index.stratio.RowIndex' " +
                        " WITH OPTIONS = {     " +
                        "                        'refresh_seconds'    : '1', " +
                        "                        'num_cached_filters' : '1', " +
                        "                        'ram_buffer_mb'      : '16', " +
                        "                        'max_merge_mb'       : '10', " +
                        "                        'max_cached_mb'      : '10', " +
                        "                        'indexing_threads'      : '1', " +
                        "                        'indexing_queues_size'      : '1000', " +
                        " 'schema' : '{ " +
                        " default_analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\", " +
                        " fields : { " +
                        " startdate : {type : \"date\"}, " +
                        " counter1 : {type : \"integer\"}, " +
                        " value1 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.ru.RussianAnalyzer\"}, " +
                        " counter2 : {type : \"bigint\"}, " +
                        " value2 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\"}, " +
                        " counter3 : {type : \"integer\"}, " +
                        " value3 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\"} " +
                        " } " +
                        " }' " +
                        " };\n");
                System.out.println("index created");
    
    
    
                final String[] str = new String[]{"1", "1 док", "1 докум", "11", "111", "1 документ в посике", "11 док",
                        "11 докум",  "111 докум",  "слова наши - просто слова", "слова поэта", "слова", "словари словари",
                        "словари", "словари словарный", "словарный", "словарный словарный словарный словарный словарный"};
                for (int i = 0; i < 4; i++) {
                    ct.getSession().execute("INSERT INTO testsort(id, counter1, value1, counter2, value2, counter3, value3, startdate) " +
                            " VALUES (1, " + i + ", '" + str[i] + "', " + i + ", 'b789', "+i+", '80b', '2014-" + (((int) (Math.random() * 11)) + 1) + "-13 15:12:51') ");
                }
    
                Thread.sleep(1000);
    
                System.out.println("Table data  =========================================");
                ResultSet res=session.execute("SELECT * FROM testsort");
                while(!res.isExhausted()){
                    Row r = res.one();
                    System.out.println(r.getInt("id")+"  "+r.getLong("counter2")+"  "+r.getString("lucene"));
                }
    
                System.out.println("Table data counter2 <> 3  =========================================");
    
                SimpleStatement st = new SimpleStatement("SELECT id, counter1, value1, counter2, value2, counter3, value3, startdate " +
                        " FROM testsort " +
                        " WHERE " +
                        " lucene='{query : {type   : \"boolean\", not : [{type : \"match\", field : \"counter2\", value : \"3\"}]} }'  ");
                res=session.execute(st);
                while(!res.isExhausted()){
                    Row r = res.one();
                    System.out.println(r.getInt("id")+"  "+r.getInt("counter1")+"  "+r.getLong("counter2")+"  "+r.getInt("counter3"));
                }
    
    
                System.out.println("Table data counter2 <> 3 AND counter2>0 =========================================");
                st = new SimpleStatement("SELECT id, counter1, value1, counter2, value2, counter3, value3, startdate " +
                        " FROM testsort " +
                        " WHERE " +
                        " lucene='{query : {type   : \"boolean\", not : [{type : \"match\", field : \"counter2\", value : \"3\"}], " +
                        " must : [{type : \"range\", field : \"counter2\", lower_value : 0}]" +
                        " } }'  ");
                res=session.execute(st);
                while(!res.isExhausted()){
                    Row r = res.one();
                    System.out.println(r.getInt("id")+"  "+r.getInt("counter1")+"  "+r.getLong("counter2")+"  "+r.getInt("counter3"));
                }
    
    
    
    
    
    
            } catch (Exception e) {
                e.printStackTrace();
            }finally {
                if(session != null ) {
    
                    session.close();
                }
                ct.close();
            }
    
        }
    
        private Cluster cluster;
        private Session session;
    
    
        public void connect(String node) {
            cluster = Cluster.builder()
                    .addContactPointsWithPorts(Collections.singleton(new InetSocketAddress(node, 9042)))
                    .withCredentials("cassandra", "cassandra").build();
            Metadata metadata = cluster.getMetadata();
            System.out.printf("Connected to cluster: %s\n",
                    metadata.getClusterName());
            for ( Host host : metadata.getAllHosts() ) {
                System.out.printf("Datacenter: %s; Host: %s; Rack: %s\n",
                        host.getDatacenter(), host.getAddress(), host.getRack());
            }
    
    
            this.session = cluster.connect();
            this.session.execute("CREATE KEYSPACE IF NOT EXISTS synergy WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };");
            this.session.execute("use synergy");
            System.out.println("session got");
        }
    
        public void reconnect(){
            this.session.close();
            this.session = cluster.connect("synergy");
        }
    
        public Session getSession(){
            return this.session;
        }
    
        public void close(){
            cluster.close();
        }
    }

**Comment by kimsashenka** [comment]
program output:
Connected to cluster: Test Cluster
Datacenter: datacenter1; Host: /127.0.0.1; Rack: rack1
session got
table created
index created
Table data  =========================================
1  0  null
1  1  null
1  2  null
1  3  null
Table data counter2 <> 3  =========================================
Table data counter2 <> 3 AND counter2>0 =========================================
1  0  0  0
1  1  1  1
1  2  2  2

**Comment by adelapena** [comment]
Pure negation queries are not supported by Lucene, as expalined in the documentation:

http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#NOT

So it is the expected behaviour. There is an opened issue in Lucene JIRA about this confusing way of working:

https://issues.apache.org/jira/browse/LUCENE-3451

Walk arounds to perform pure negation queries are explained here:

http://kb.ucla.edu/articles/pure-negation-query-in-lucene

I have added a "match_all" condition in develop branch to support this type of queries this way:
```
SELECT * FROM testsort WHERE  lucene=
'{query :  { type : "boolean", 
    not : [{ type : "match", field : "counter2", value : "3"}],
   must : [{ type : "match_all" }]
 } }' ;
```
It will be available on master branch and Maven repository as soon as possible.

Regardless of all this, I see that you are using Stratio's bigint to map the counter2 column, which is defined as CQL bigint. CQL bigint wraps a Java Long (which is a little bit confusing), so you will get a better performance using long mapping for counter2 bigint column. Stratio's bingint mapping is intended for arbitrary length integers stored in CQL text fields.
```
CREATE TABLE IF NOT EXISTS testsort(
	id int, 
	counter1 int, 
	value1 text, 
	counter2 bigint, 
	value2 text, 
	counter3 int, 
	value3 text, 
	startdate timestamp, 
	lucene text,  
PRIMARY KEY(id, counter1, value1, counter2)) 
WITH CLUSTERING ORDER BY (counter1 asc, value1 asc, counter2 asc);

CREATE CUSTOM INDEX  IF NOT EXISTS testsort_lucene ON testsort (lucene)  
USING 'org.apache.cassandra.db.index.stratio.RowIndex'  
WITH OPTIONS = {                             
'refresh_seconds'    : '1',                         
'num_cached_filters' : '1',                         
'ram_buffer_mb'      : '16',                         
'max_merge_mb'       : '10',                         
'max_cached_mb'      : '10',                         
'indexing_threads'      : '1',                         
'indexing_queues_size'      : '1000',  
'schema' : '{  
	default_analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer",  
	fields : {  startdate : {type : "date"},  
		counter1 : {type : "integer"},  
		value1 : {type: "text", analyzer : "org.apache.lucene.analysis.ru.RussianAnalyzer"},  
		counter2 : {type : "long"},  
		value2 : {type: "text", 
		analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer"},  
		counter3 : {type : "integer"},  
		value1alue3 : {type: "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer"}  
		}  
	}'  
};
```

**Comment by kimsashenka** [comment]
Thank you!
