### ISSUE TITLE
Support for snowball and possibly other analyzers available in lucene

### ISSUE THREAD

**Issue by masumsoft** [Stratio/stratio-cassandra#11]
Looks like the current build doesn't support snowball analyzer and other lucene analyzers except some core standard analyzers. It would be great if other analyzers were supported.

**Comment by adelapena** [comment]
You are right, it would be a nice feature. We will add support for snowball and other analyzers as soon as possible. Thanks!

**Comment by Bangsheng** [comment]
Is there a list of analyzers supported now? And I can't find a way to do case insensitive queries. Is there an case insensitive analyzer?

**Comment by masumsoft** [comment]
@Bangsheng standard analyzer should be case insensitive, what I discovered is you just need to use data type "text" instead of "string" in your schema definition. The data type "string" tries to find exact matches.

**Comment by Bangsheng** [comment]
@masumsoft Yes, you are right. But I am wondering whether there are any analyzer for something like 'case insensitive string' which takes the entire value as one token and case insensitive.

**Comment by adelapena** [comment]
The current available tokenizers are those defined in [lucene-analyzers-common](http://lucene.apache.org/core/4_8_1/analyzers-common/index.html). They are instantiated by reflection using the specified class name:
```
Class<?> analyzerClass = Class.forName(analyzerClassName);
Constructor<?> constructor = analyzerClass.getConstructor(Version.class);
analyzer = (Analyzer) constructor.newInstance(Version.LUCENE_48);
```
No constructor arguments or additional arguments are used, so currently no Tokenizer or TokenizerFilter can be specified.  This would indeed be a very nice feature, so we are going extend the syntax of the index in order to support it, in a similar way as it is done in Solr. I think that it will be available in no longer than a couple of weeks.

Until then, as a wall around, you can create a class extending org.apache.lucene.analysis.Analyzer with a default constructor using the desired tokenizer. If you add this class to the classpath of Stratio Cassandra, you could instantiate it by its fully qualified name when creating the index.

**Comment by adelapena** [comment]
@Bangsheng I have added a ```case_sensitive``` option to ```string``` mapper. The default value is ```true```, if you set it to ```false``` the mapping will be case insensitive. For example:
```
CREATE CUSTOM INDEX tweets_index ON tweets (lucene)
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
    'refresh_seconds'    : '1',
    'schema' : '{
        fields : {
            user : {type : "string", case_sensitive: false},
            body : {type : "text",  analyzer : "org.apache.lucene.analysis.en.EnglishAnalyzer"}
        }
    }'
};
```
This new feature is in the [develop](https://github.com/Stratio/stratio-cassandra/tree/develop) branch. I hope you find it useful. Of course, the future syntax for creating custom analyzers will be much more powerful than this.

**Comment by Bangsheng** [comment]
@adelapena Thanks.

**Comment by jacekskrzypiec** [comment]
Can I analyse the same column with two different analyzers and  and create to different fields in lucene index?

**Comment by adelapena** [comment]
Not currently. There are plans to improve mappers in order to specify the name of the Lucene field to be created so you could apply multiple mappings on a single column, but currently mapping between Cassandra columns and Lucene fields is one to one. Of course, for the time being, you can store the column twice and apply a different mapping/analyzer to each column.

**Comment by jacekskrzypiec** [comment]
Thank you for letting me know.

**Comment by adelapena** [comment]
As promised, we have just added support for snowball analyzer. We have added an "analyzers" argument to the index schema definition that can be used for this purpose. In the near future, it will be used for defining other custom analyzers. Given the next table definition:
```
CREATE KEYSPACE demo
         WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
         
CREATE TABLE demo.users (
  id int,
  spanish_text text,
  snowball_text text,
  lucene text,
  PRIMARY KEY (id));
```
You can create the index with snowball analyzer this way:
```
CREATE CUSTOM INDEX demo_lucene ON  demo.users (lucene) USING 'com.stratio.cassandra.index.RowIndex' WITH OPTIONS = {
'refresh_seconds':'1', 
'schema':'{
  analyzers:{
    spanish_analyzer : {type:"classpath", class:"org.apache.lucene.analysis.es.SpanishAnalyzer"},
    snowball_analyzer : {type:"snowball", language:"Spanish", stopwords : "el,la,lo,loas,las,a,ante,bajo,cabe,con,contra"}
  },
  default_analyzer : "spanish_analyzer",
  fields : {
    id : {type : "integer"},
    spanish_text : {type:"text", analyzer:"spanish_analyzer"},
    snowball_text : {type:"text", analyzer:"snowball_analyzer"}
  }
 }'};
```
So, the column "snowball_text" will use the snowball analyzer named "snowball_analyzer" with the specified language and stopwords. If you do not specify a stopwords list, then the default language stopwords will be used.

You can see the stemming differences between analyzers inserting some data: 
```
INSERT INTO demo.users (id, spanish_text, snowball_text) VALUES ( 1, 'perder', 'perder');
INSERT INTO demo.users (id, spanish_text, snowball_text) VALUES ( 2, 'perdido', 'perdido');
```
and then querying:
```
SELECT * FROM demo.users WHERE lucene='{filter:{type:"match", field:"spanish_text", value:"perder"}}';
SELECT * FROM demo.users WHERE lucene='{filter:{type:"match", field:"snowball_text", value:"perder"}}';
```
The changes are available in the branch [custom analyzers](https://github.com/Stratio/stratio-cassandra/tree/feature/custom-analyzers), and will be merged in the next stable version ASAP.

**Comment by masumsoft** [comment]
Excellent :+1:

**Comment by adelapena** [comment]
Support for snowball analyzer is now available in the stable version, tagged as [stratio-cassandra-2.1.4.0](https://github.com/Stratio/stratio-cassandra/tree/stratio-cassandra-2.1.4.0). Support for other analyzers, as [PatternAnalyzer] (http://lucene.apache.org/core/4_10_0/analyzers-common/org/apache/lucene/analysis/miscellaneous/PatternAnalyzer.html), is in roadmap and will be added in future releases ASAP.
