### ISSUE TITLE
Comprehensive documentation link at bottom of wiki leads to site with no content

### ISSUE THREAD

**Issue by sstgithub** [Stratio/stratio-cassandra#13]
"Please, refer to the comprehensive Stratio Cassandra documentation at Stratio website." leads to http://www.openstratio.org/manuals/extended-search-in-cassandra/ which just has: "This website is currently deprecated."

**Comment by adelapena** [comment]
We are updating the Stratio web site and some links are temporarily broken, apologies for the inconvenience.
Current documentation can be found in the project itself:
  https://github.com/Stratio/stratio-cassandra/blob/master/doc/stratio/extended-search-in-cassandra.md
I have updated the README to point to it. It will link to the new Stratio web site ASAP.

Thanks!

**Comment by sstgithub** [comment]
Thanks for adding the documentation!
