### ISSUE TITLE
Vulnerability of Cassandra

### ISSUE THREAD

**Issue by jamsheer-citrus** [Stratio/stratio-cassandra#16]
A Vulnerability found with Cassandra Versions 1.2.0 to 1.2.19, 2.0.0 to 2.0.13, and 2.1.0 to 2.1.3  . http://packetstormsecurity.com/files/131249/Apache-Cassandra-Remote-Code-Execution.html. So i would like to know the current version of Cassandra using stratio-cassandra project ?

**Comment by craveica** [comment]
Currently it's 2.1.3.

**Comment by jamsheer-citrus** [comment]
Thank you for your valuable feedback

**Comment by adelapena** [comment]
I have just upgraded to 2.1.4, it is tagged as [stratio-cassandra-2.1.4.0](https://github.com/Stratio/stratio-cassandra/tree/stratio-cassandra-2.1.4.0) and synced with master. Thanks!

**Comment by jamsheer-citrus** [comment]
Good work.thanks again
