### ISSUE TITLE
Issue with search key

### ISSUE THREAD

**Issue by jamsheer-citrus** [Stratio/stratio-cassandra#18]
I am getting error while executing following  query, 

  SELECT  *  FROM  test WHERE lucene='{query :  {type : "match", field : "URL", value :"AAAA-BBB-943b7a01b257d1a1af3441d0639c9a2dc65562a8"}}'

But its working if i remove '-' from the key ,Is it possible to use key with - .
My working query is ,

SELECT  *  FROM  test WHERE lucene='{query :  {type : "match", field : "URL", value :"AAAABBB943b7a01b257d1a1af3441d0639c9a2dc65562a8"}}'

Thanks

**Comment by adelapena** [comment]
Could you please show me the create table and create index statements? I need to know at least the type of the column 'URL' and the used index mapper in order to reproduce the issue.

**Comment by jamsheer-citrus** [comment]
You may reproduce with following queries ,


    CREATE KEYSPACE demoWITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE tweets (    id INT PRIMARY KEY,    user TEXT,    body TEXT,    time TIMESTAMP,
    lucene TEXT
);


CREATE CUSTOM INDEX tweets_index ON tweets (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id   : {type : "integer"},
            user : {type : "string"},
            body : {type : "text"},
            time : {type : "date", pattern  : "yyyy/MM/dd"}
        }
    }'
};



      INSERT INTO tweets	(id, body, lucene, time, user)VALUES 	(1, 'test', '', '2015-01-01', 'user1');
	
	INSERT INTO tweets	(id, body, lucene, time, user)VALUES 	(2, 'AAAA-BBB-943b7a01b257d1a1af3441d0639c9a2dc65562a8', '', '2015-01-01', 'user2');

SELECT * FROM tweets
WHERE lucene = '{query : {
                        type  : "match",
                        field : "body",
                        value : "test" }}';
                        

But i am getting error with following select query

SELECT * FROM tweets
WHERE lucene = '{query : {
                        type  : "match",
                        field : "body",
                        value : "AAAA-BBB-943b7a01b257d1a1af3441d0639c9a2dc65562a8" }}';

**Comment by adelapena** [comment]
The field "body" is using a "text" mapper, which is used for analyzed text. No analyzer is specified in the schema, so the default analyzer is used. This is Lucene's [StandardAnalyzer](http://lucene.apache.org/core/4_8_0/analyzers-common/org/apache/lucene/analysis/standard/StandardAnalyzer.html), which uses hyphen as token separator. This way, the text "AAAA-BBB-943b7a01b257d1a1af3441d0639c9a2dc65562a8" is split into three tokens, which are "AAAA", "BBB" and "943b7a01b257d1a1af3441d0639c9a2dc65562a8". The provided query is of type "match", which is used for matching single terms. You can see that theses queries do find the row:
```
SELECT * FROM tweets WHERE lucene = '{query : 
   {type : "match", field : "body", value :"AAAA"}}';
SELECT * FROM tweets WHERE lucene = '{query : 
   {type : "match", field : "body", value :"BBB"}}';
SELECT * FROM tweets WHERE lucene = '{query : 
   {type : "match", field : "body", value :"943b7a01b257d1a1af3441d0639c9a2dc65562a8"}}';
```
Additionally, you can query for all the three terms using a phrase query, which is intended to multi term searches: 
```
SELECT * FROM tweets WHERE lucene = 
   '{query : {
      type : "phrase", 
      field : "body", 
      values :["AAAA", "BBB", "943b7a01b257d1a1af3441d0639c9a2dc65562a8"]}}';
```
Also you can use the Lucene's query syntax:
```
SELECT * FROM tweets WHERE lucene = 
   '{query : {
      type : "lucene", 
      default_field : "body", 
      query :"AAAA-BBB-943b7a01b257d1a1af3441d0639c9a2dc65562a8"}}';
```
Alternatively, if you are not interested in language analysis, you can map the field body as "string":
```
CREATE CUSTOM INDEX tweets_index ON tweets (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
'refresh_seconds' : '1',
'schema' : '{
fields : {
  id : {type : "integer"},
  user : {type : "string"},
  body : {type : "string"},
  time : {type : "date", pattern : "yyyy/MM/dd"}
}}'};
```
Thus you can use the match query as is:
```
SELECT * FROM tweets
WHERE lucene = '{query : {
   type : "match",
   field : "body",
   value : "AAAA-BBB-943b7a01b257d1a1af3441d0639c9a2dc65562a8" }}';
```
And also do wildcard queries:
```
SELECT * FROM tweets WHERE lucene = '{query : 
   {type : "wildcard", field : "body", value :"AAAA*"}}';
SELECT * FROM tweets WHERE lucene = '{query : 
   {type : "wildcard", field : "body", value :"*BBB*"}}';
```

**Comment by jamsheer-citrus** [comment]
Thank you for the feed back
