### ISSUE TITLE
Distinct query with where clause 

### ISSUE THREAD

**Issue by jamsheer-citrus** [Stratio/stratio-cassandra#19]
Is it possible to restrict select distinct by adding something in where
part?

**Comment by adelapena** [comment]
You can restrict select distinct adding *not* clauses to a boolean query/filter. For example, to search for tweets within a certain date range written by users whose name doesn't start with "a":
```
SELECT * FROM tweets WHERE  lucene=
'{filter : {  type : "boolean", 
               not : [ { type : "prefix", field : "user", value : "a"} ],
              must : [ { type : "range",  field : "time", lower : "2014/04/25" } ]
           }
 }' ;
```
However, as discussed at issue #10, pure negation queries are not supported by Lucene. As a walk around, you can add a *match_all* clause to the boolean query:
```
SELECT * FROM tweets WHERE  lucene=
'{filter : {  type : "boolean", 
               not : [ { type : "prefix", field : "user", value : "a"} ],
              must : [ { type : "match_all" } ]
           }
 }' ;
```
I hope this answers your question.

**Comment by jamsheer-citrus** [comment]
Thank you for the reply.This solution not enough to meet my scenario,Because i want remove remove repeated record from the result set.Is it possible  ??

**Comment by jamsheer-citrus** [comment]
shall we use any field with 'distinct ' name instead * in above query .
Example
SELECT distinct body FROM tweets WHERE  lucene=
'{filter : {  type : "boolean", 
               not : [ { type : "prefix", field : "user", value : "a"} ],
              must : [ { type : "range",  field : "time", lower : "2014/04/25" } ]
           }
 }' ;

**Comment by adelapena** [comment]
Oh, I'm sorry, now I understand your question. The Lucene based indexes are only suitable for filtering rows. So no, they do not provide anything equivalent to SQL's DISTINCT. CQL provides by itself a SELECT DISTINCT functionality, but it can only be used with partition key fields. I think that you may use one of the Spark & Cassandra integration solutions for this.

**Comment by jamsheer-citrus** [comment]
Thank you @Adelapena
