### ISSUE TITLE
Deleet query is slow 

### ISSUE THREAD

**Issue by jamsheer-citrus** [Stratio/stratio-cassandra#21]
I need to delete a record from my table as per my requirement.But CQL delete query is too slow here after index is crated .I think i made some mistake during index creation ,Any clue ??
Thanks in advance

**Comment by adelapena** [comment]
Can you please show your schema and the deletion query? How many rows are in the table? How slow is the query?

**Comment by jamsheer-citrus** [comment]
Issue was with my indexing ,thanks
