### ISSUE TITLE
How to compile the source  code

### ISSUE THREAD

**Issue by xifengwang** [Stratio/stratio-cassandra#26]
Hello!
    When I compile the source code 2.1.4.1 using Ant1.9.2,I get a result as "Build Failure" Here is the detail:

Buildfile: /home/wangfvgherpeng/stratio-cassandra-master/build.xml

init:
    [mkdir] Created dir: /home/wangfvgherpeng/stratio-cassandra-master/build/classes/main
    [mkdir] Created dir: /home/wangfvgherpeng/stratio-cassandra-master/build/classes/thrift
    [mkdir] Created dir: /home/wangfvgherpeng/stratio-cassandra-master/build/test/lib
    [mkdir] Created dir: /home/wangfvgherpeng/stratio-cassandra-master/build/test/classes
    [mkdir] Created dir: /home/wangfvgherpeng/stratio-cassandra-master/src/gen-java
    [mkdir] Created dir: /home/wangfvgherpeng/stratio-cassandra-master/build/lib

maven-ant-tasks-localrepo:

maven-ant-tasks-download:
     [echo] Downloading Maven ANT Tasks...
      [get] Getting: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] To: /home/wangfvgherpeng/stratio-cassandra-master/build/maven-ant-tasks-2.1.3.jar

maven-ant-tasks-init:

maven-declare-dependencies:

maven-ant-tasks-retrieve-build:
[artifact:dependencies] Downloading: junit/junit/4.6/junit-4.6.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'junit:junit:pom:4.6' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: junit/junit/4.6/junit-4.6.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'junit:junit:pom:4.6' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: junit/junit/4.6/junit-4.6.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'junit:junit:pom:4.6' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: org/slf4j/slf4j-api/1.5.2/slf4j-api-1.5.2.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.slf4j:slf4j-api:pom:1.5.2' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: org/slf4j/slf4j-api/1.5.2/slf4j-api-1.5.2.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'org.slf4j:slf4j-api:pom:1.5.2' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: org/slf4j/slf4j-api/1.5.2/slf4j-api-1.5.2.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'org.slf4j:slf4j-api:pom:1.5.2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/sun/jersey/jersey-server/1.0/jersey-server-1.0.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.sun.jersey:jersey-server:pom:1.0' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: com/sun/jersey/jersey-server/1.0/jersey-server-1.0.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.sun.jersey:jersey-server:pom:1.0' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/sun/jersey/jersey-server/1.0/jersey-server-1.0.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.sun.jersey:jersey-server:pom:1.0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: junit/junit/4.8.1/junit-4.8.1.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'junit:junit:pom:4.8.1' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: junit/junit/4.8.1/junit-4.8.1.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'junit:junit:pom:4.8.1' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: junit/junit/4.8.1/junit-4.8.1.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'junit:junit:pom:4.8.1' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.google.code.findbugs:jsr305:pom:2.0.2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.google.code.findbugs:jsr305:pom:2.0.2' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.google.code.findbugs:jsr305:pom:2.0.2' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: org/antlr/antlr/3.5.2/antlr-3.5.2.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'org.antlr:antlr:pom:3.5.2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: org/antlr/antlr/3.5.2/antlr-3.5.2.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.antlr:antlr:pom:3.5.2' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: org/antlr/antlr/3.5.2/antlr-3.5.2.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'org.antlr:antlr:pom:3.5.2' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/datastax/cassandra/cassandra-driver-core/2.0.5/cassandra-driver-core-2.0.5.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.datastax.cassandra:cassandra-driver-core:pom:2.0.5' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/datastax/cassandra/cassandra-driver-core/2.0.5/cassandra-driver-core-2.0.5.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.datastax.cassandra:cassandra-driver-core:pom:2.0.5' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: com/datastax/cassandra/cassandra-driver-core/2.0.5/cassandra-driver-core-2.0.5.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.datastax.cassandra:cassandra-driver-core:pom:2.0.5' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: net/ju-n/compile-command-annotations/compile-command-annotations/1.2.0/compile-command-annotations-1.2.0.pom from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'net.ju-n.compile-command-annotations:compile-command-annotations:pom:1.2.0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: net/ju-n/compile-command-annotations/compile-command-annotations/1.2.0/compile-command-annotations-1.2.0.pom from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'net.ju-n.compile-command-annotations:compile-command-annotations:pom:1.2.0' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: net/ju-n/compile-command-annotations/compile-command-annotations/1.2.0/compile-command-annotations-1.2.0.pom from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'net.ju-n.compile-command-annotations:compile-command-annotations:pom:1.2.0' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: junit/junit/4.6/junit-4.6.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Downloading: com/datastax/cassandra/cassandra-driver-core/2.0.5/cassandra-driver-core-2.0.5.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'junit:junit:jar:4.6' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.datastax.cassandra:cassandra-driver-core:jar:2.0.5' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Downloading: com/datastax/cassandra/cassandra-driver-core/2.0.5/cassandra-driver-core-2.0.5.jar from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.google.code.findbugs:jsr305:jar:2.0.2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/sun/jersey/jersey-server/1.0/jersey-server-1.0.jar from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Downloading: junit/junit/4.6/junit-4.6.jar from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Downloading: com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.jar from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Downloading: net/ju-n/compile-command-annotations/compile-command-annotations/1.2.0/compile-command-annotations-1.2.0.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: net/ju-n/compile-command-annotations/compile-command-annotations/1.2.0/compile-command-annotations-1.2.0.jar from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.google.code.findbugs:jsr305:jar:2.0.2' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: com/google/code/findbugs/jsr305/2.0.2/jsr305-2.0.2.jar from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.google.code.findbugs:jsr305:jar:2.0.2' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: org/antlr/antlr/3.5.2/antlr-3.5.2.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'org.antlr:antlr:jar:3.5.2' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: org/antlr/antlr/3.5.2/antlr-3.5.2.jar from repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.sun.jersey:jersey-server:jar:1.0' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: com/sun/jersey/jersey-server/1.0/jersey-server-1.0.jar from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.sun.jersey:jersey-server:jar:1.0' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Downloading: com/sun/jersey/jersey-server/1.0/jersey-server-1.0.jar from repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.sun.jersey:jersey-server:jar:1.0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Network is unreachable
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.antlr:antlr:jar:3.5.2' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: org/antlr/antlr/3.5.2/antlr-3.5.2.jar from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'org.antlr:antlr:jar:3.5.2' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: net/ju-n/compile-command-annotations/compile-command-annotations/1.2.0/compile-command-annotations-1.2.0.jar from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'com.datastax.cassandra:cassandra-driver-core:jar:2.0.5' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: com/datastax/cassandra/cassandra-driver-core/2.0.5/cassandra-driver-core-2.0.5.jar from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'com.datastax.cassandra:cassandra-driver-core:jar:2.0.5' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'junit:junit:jar:4.6' in repository apache (https://repository.apache.org/content/repositories/releases)
[artifact:dependencies] Downloading: junit/junit/4.6/junit-4.6.jar from repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Error transferring file: Network is unreachable
[artifact:dependencies] [WARNING] Unable to get resource 'junit:junit:jar:4.6' from repository java.net2 (http://download.java.net/maven/2): Error transferring file: Network is unreachable
[artifact:dependencies] An error has occurred while processing the Maven artifact tasks.
[artifact:dependencies]  Diagnosis:
[artifact:dependencies] 
[artifact:dependencies] Unable to resolve artifact: Missing:
[artifact:dependencies] ----------
[artifact:dependencies] 1) com.google.code.findbugs:jsr305:jar:2.0.2
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=com.google.code.findbugs -DartifactId=jsr305 -Dversion=2.0.2 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=com.google.code.findbugs -DartifactId=jsr305 -Dversion=2.0.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]         1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies]         2) com.google.code.findbugs:jsr305:jar:2.0.2
[artifact:dependencies] 
[artifact:dependencies] 2) com.sun.jersey:jersey-server:jar:1.0
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=com.sun.jersey -DartifactId=jersey-server -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=com.sun.jersey -DartifactId=jersey-server -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]         1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies]         2) org.apache.hadoop:hadoop-minicluster:jar:1.0.3
[artifact:dependencies]         3) com.sun.jersey:jersey-server:jar:1.0
[artifact:dependencies] 
[artifact:dependencies] 3) org.antlr:antlr:jar:3.5.2
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=org.antlr -DartifactId=antlr -Dversion=3.5.2 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=org.antlr -DartifactId=antlr -Dversion=3.5.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]         1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies]         2) org.antlr:antlr:jar:3.5.2
[artifact:dependencies] 
[artifact:dependencies] 4) net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=net.ju-n.compile-command-annotations -DartifactId=compile-command-annotations -Dversion=1.2.0 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=net.ju-n.compile-command-annotations -DartifactId=compile-command-annotations -Dversion=1.2.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]         1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies]         2) net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0
[artifact:dependencies] 
[artifact:dependencies] 5) com.datastax.cassandra:cassandra-driver-core:jar:2.0.5
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=com.datastax.cassandra -DartifactId=cassandra-driver-core -Dversion=2.0.5 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=com.datastax.cassandra -DartifactId=cassandra-driver-core -Dversion=2.0.5 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]         1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies]         2) com.datastax.cassandra:cassandra-driver-core:jar:2.0.5
[artifact:dependencies] 
[artifact:dependencies] 6) junit:junit:jar:4.6
[artifact:dependencies] 
[artifact:dependencies]   Try downloading the file manually from the project website.
[artifact:dependencies] 
[artifact:dependencies]   Then, install it using the command: 
[artifact:dependencies]       mvn install:install-file -DgroupId=junit -DartifactId=junit -Dversion=4.6 -Dpackaging=jar -Dfile=/path/to/file
[artifact:dependencies] 
[artifact:dependencies]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:dependencies]       mvn deploy:deploy-file -DgroupId=junit -DartifactId=junit -Dversion=4.6 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:dependencies] 
[artifact:dependencies]   Path to dependency: 
[artifact:dependencies]         1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies]         2) junit:junit:jar:4.6
[artifact:dependencies] 
[artifact:dependencies] ----------
[artifact:dependencies] 6 required artifacts are missing.
[artifact:dependencies] 
[artifact:dependencies] for artifact: 
[artifact:dependencies]   com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
[artifact:dependencies] 
[artifact:dependencies] from the specified remote repositories:
[artifact:dependencies]   central (http://repo1.maven.org/maven2),
[artifact:dependencies]   apache (https://repository.apache.org/content/repositories/releases),
[artifact:dependencies]   java.net2 (http://download.java.net/maven/2)
[artifact:dependencies] 
[artifact:dependencies] 
BUILD FAILED
/home/wangerxerpeng/stratio-cassandra-master/build.xml:579: Unable to resolve artifact: Missing:
----------
1) com.datastax.cassandra:cassandra-driver-core:jar:2.0.5

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.datastax.cassandra -DartifactId=cassandra-driver-core -Dversion=2.0.5 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.datastax.cassandra -DartifactId=cassandra-driver-core -Dversion=2.0.5 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
        2) com.datastax.cassandra:cassandra-driver-core:jar:2.0.5

2) junit:junit:jar:4.6

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=junit -DartifactId=junit -Dversion=4.6 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=junit -DartifactId=junit -Dversion=4.6 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
        2) junit:junit:jar:4.6

3) org.antlr:antlr:jar:3.5.2

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.antlr -DartifactId=antlr -Dversion=3.5.2 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.antlr -DartifactId=antlr -Dversion=3.5.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
        2) org.antlr:antlr:jar:3.5.2

4) com.google.code.findbugs:jsr305:jar:2.0.2

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.google.code.findbugs -DartifactId=jsr305 -Dversion=2.0.2 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.google.code.findbugs -DartifactId=jsr305 -Dversion=2.0.2 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
        2) com.google.code.findbugs:jsr305:jar:2.0.2

5) net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=net.ju-n.compile-command-annotations -DartifactId=compile-command-annotations -Dversion=1.2.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=net.ju-n.compile-command-annotations -DartifactId=compile-command-annotations -Dversion=1.2.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
        2) net.ju-n.compile-command-annotations:compile-command-annotations:jar:1.2.0

6) com.sun.jersey:jersey-server:jar:1.0

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=com.sun.jersey -DartifactId=jersey-server -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=com.sun.jersey -DartifactId=jersey-server -Dversion=1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT
        2) org.apache.hadoop:hadoop-minicluster:jar:1.0.3
        3) com.sun.jersey:jersey-server:jar:1.0

----------
6 required artifacts are missing.

for artifact: 
  com.stratio.cassandra:cassandra-build-deps:jar:2.1.4.1-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  apache (https://repository.apache.org/content/repositories/releases),
  java.net2 (http://download.java.net/maven/2)

**Comment by adelapena** [comment]
I can successfully build it with Ant 1.9.2 and JDK 1.7.0_75. Your Ant output is showing the error message "Network is unreachable" several times, so it seems that you have a problem with your Internet connection when Ant tries to download the dependencies of the project. I guess that it is the same problem reported in issue #25, right?
