### ISSUE TITLE
Versioning in stratio Cassandra

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/stratio-cassandra#27]
Hi,
I would like know that, is there any ways to implement the versioning in stratio-cassandra? 

Thanks

**Comment by adelapena** [comment]
What do you mean by versioning? Something like [Elasticsearch's versioning](https://www.elastic.co/blog/elasticsearch-versioning-support)?

**Comment by justinjoseph89** [comment]
yes just like Elasticsearch versioning. I just want to keep the history of my data.

**Comment by adelapena** [comment]
Ok. No, Stratio Cassandra does not provide this feature. Alternatively, if it is appropriate for your use case, you could save historical data in a separate table, while keeping the current state of your data in a different small and fast table. Of course, both tables could be indexed.

**Comment by justinjoseph89** [comment]
Thanks
