### ISSUE TITLE
Not being able to perform 'SELECT' statement

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/stratio-cassandra#31]
Hi,
I have been using startio-Cassandra for a while, and i  successfully implemented all of my implementations . But today i inserted a data of approximately 560KB in a column of cassandra columnfamily, data inserted without any issues, but now i cant able to retrieve the same data. I have read some suggestions to avoid this, but i coudnt really figure it out. Is there any way i can avoid this?

Thanks

**Comment by adelapena** [comment]
Hi,

Can you give more information about your schema and the row/column that you can not retrieve? This way I can try to reproduce the problem.

Thanks

**Comment by justinjoseph89** [comment]
Hi,
This is how i created my schema

CREATE KEYSPACE z_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3}

Then i created a table 

CREATE TABLE z_test.example (
	id text,
	name text,
	age text,
	data text,
	lucene text,
	PRIMARY KEY (id,name,age)
);

Then Created the index for the table,


CREATE CUSTOM INDEX idx_example ON z_test.example (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id   : {type : "string"},
            data : {type : "string"},
            name : {type : "string"},
            age : {type : "string"}
        }
    }'
};

Now i am inserting two data into the table

INSERT INTO z_test.example
	(id, name, age, data)
VALUES 
	('2', 'b', '2', 'good_dat');


INSERT INTO z_test.example
	(id, name, age, data)
VALUES 
	('1', 'a', '1', 'LARGE_DATA');

Where ''LARGE_DATA' means a json string which exceeds  size of 600KB.

Now i want select the data  so i wrote the query like this,
 SELECT *  FROM example WHERE lucene='{query :  {type : "boolean",  
                        must : [
                               {type : "match", field : "id", value :"2"},                               
                               {type : "match", field : "name", value :"b"}
                              ]}}';
It works just fine. But now i want to select the row where large data is present

SELECT *  FROM example WHERE lucene='{query :  {type : "boolean",  
                        must : [
                               {type : "match", field : "id", value :"1"},                               
                               {type : "match", field : "name", value :"a"}
                              ]}}';

But it doesn't return any data, but if i try the below query i will get the exact data,

SELECT *  FROM example where id='1';

Why this is happening ? Is there any mistakes in my side while indexing?

**Comment by adelapena** [comment]
I have reproduced the problem with [2.1.5.0](https://github.com/Stratio/stratio-cassandra/tree/stratio-cassandra-2.1.5.0), which is the last stable version. Indeed, CQL does not report the error but the log output shows this error message:

``
ERROR 10:23:35 Error while indexing row 31
WARN  10:23:35 Uncaught exception on thread Thread[SharedPool-Worker-2,10,main]: {}
java.lang.RuntimeException: java.lang.IllegalArgumentException: ``**Document contains at least one immense term**`` in field="data" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[91, 34, 102, 48, 54, 101, 100, 102, 102, 54, 45, 98, 98, 100, 97, 45, 52, 48, 98, 57, 45, 57, 55, 49, 56, 45, 52, 98, 97, 54]...', original message: bytes can be at most 32766 in length; got 195001
``

However, the wrong error reporting is solved at [develop branch](https://github.com/Stratio/stratio-cassandra/tree/develop), so next release will send the error to CQL clients.

Regarding the indexing error itself, you are trying to index a large field using a ``string`` mapper, which is a ``text`` mapper using a Lucene's [KeywordAnalyzer](http://lucene.apache.org/core/4_4_0/analyzers-common/org/apache/lucene/analysis/core/KeywordAnalyzer.html). This kind of analyzer maps all the column contents to a single Lucene [term](https://lucene.apache.org/core/4_2_0/core/org/apache/lucene/index/Term.html), which has a maximum size that must not be exceeded. Depending on your searching needs, you could use a text mapper with a proper analyzer or, alternatively, split the JSON column in several CQL columns with proper mappers.

**Comment by justinjoseph89** [comment]
Thank you for your reply. So i would like to know that , is there any size limit for a single field value? Because i can be able to insert the data but cannot retrieve .

Actually i dont want to neither select the data nor gives in the where condition.

SELECT name FROM example WHERE lucene='{query : {type : "boolean",

must : [
{type : "match", field : "id", value :"1"},
{type : "match", field : "name", value :"a"}
]}}';

So there is no way for this?

**Comment by adelapena** [comment]
You can't retrieve the row because it is not being indexed, it is failing silently (just logging). The next version of Stratio Cassandra will report the error more clearly. 

Indexing fails with columns mapped as ``string`` containing more than 32766 characters, as reported by the log output. If you are not interested in querying by the value of ``data`` you can remove it from the index mapping schema:
```
CREATE CUSTOM INDEX idx_example ON z_test.example (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
'refresh_seconds' : '1',
'schema' : '{
fields : {
id : {type : "string"},
name : {type : "string"},
age : {type : "string"}
}
}'
};
```
Alternatively, if you are interested in doing queries including restrictions over the value of ``data``, then you should index it as tokenized ``text`` instead of as not tokenized ``string``, e.g.:
```
CREATE CUSTOM INDEX idx_example ON z_test.example (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
'refresh_seconds' : '1',
'schema' : '{
fields : {
id : {type : "string"},
data : {type : "text", analyzer : "whitespace"},
name : {type : "string"},
age : {type : "string"}
}
}'
};
```

**Comment by justinjoseph89** [comment]
Thanks it worked .
