### ISSUE TITLE
How to search data with an empty string or null value?

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/stratio-cassandra#32]
Hi,
I have a column family which contains empty string in a column. Now i want to find those rows with empty string. I am giving an example.

CREATE KEYSPACE demo WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE tweets (
    id INT PRIMARY KEY,
    user TEXT,
    body TEXT,
    time TIMESTAMP,
    lucene TEXT
);

CREATE CUSTOM INDEX tweets_index ON tweets (lucene) 
USING 'com.stratio.cassandra.index.RowIndex'
WITH OPTIONS = {
    'refresh_seconds' : '1',
    'schema' : '{
        fields : {
            id   : {type : "integer"},
            user : {type : "string"},
            body : {type : "text",  analyzer : "english"},
            time : {type : "date", pattern  : "yyyy/MM/dd"}
        }
    }'
};

Now insert the data

INSERT INTO demo.tweets
	(id, body, user)
VALUES 
	(1, 'body1', 'user1');
	
	
INSERT INTO demo.tweets
	(id, body, user)
VALUES 
	(2, '', 'user2');
	
	INSERT INTO demo.tweets
	(id, body, user)
VALUES 
	(3, 'body3', '');

Now i want to select the rows when user='' 
SELECT * FROM tweets WHERE lucene='{
    query : {type:"match", field:"user", value:"''"}
}' 

But it is not working . Is there any issues in my side?

**Comment by adelapena** [comment]
You can use a range query:
```
SELECT * FROM tweets WHERE lucene='{ 
   query : {type:"range", field:"user", upper:"",include_upper:true} }';
``` 
We will try to improve the match query behavior in the next release.

**Comment by justinjoseph89** [comment]
Thanks . It worked.
