### ISSUE TITLE
Altering The Existing Index

### ISSUE THREAD

**Issue by justinjoseph89** [Stratio/stratio-cassandra#33]
Hi,
I would like to know that is there any ways to alter the existing index. My case is that i have a column family and an index, and now i want to add a new column to it . Is there any way to add index for that column? . And also i need to know that once i inserted the data, i am going to delete the indexing to create a new indexing, will that indexing effect the column family?

Thanks

**Comment by adelapena** [comment]
Hi,

There is no way to alter the schema of an existing index. There are no plans in the near future to offer this feature. At least, there will not while Apache Cassandra is not providing alter index statements.

If you want to index a new column, or to modify the index in any other way, you must drop the existing index and create a new one with the desired schema. All the previously existent data in the column family will be indexed in the background. The log output will notify you when the index built is complete.

The indexed column family will not be modified in any case.

**Comment by justinjoseph89** [comment]
Thank you for the reply.
I have a column family with more than one lakh data, to remove index for a column i dropped the index and created it once again. Now my queries are not working. What would be the issue?

**Comment by adelapena** [comment]
Index build can take some time. Depending on your hardware and your schema, indexing one [lakh](http://en.wikipedia.org/wiki/Lakh) can take some time. Have you seen a message like ``Index build of <index_name> complete`` in the Cassandra log file before doing your queries? Is the log file reporting any error?

**Comment by justinjoseph89** [comment]
Thanks for the reply.
