### ISSUE TITLE
indexing_threads wrong value

### ISSUE THREAD

**Issue by kimsashenka** [Stratio/stratio-cassandra#4]
when i'm trying to create an index with indexing_threads=0, i get the following error.

<ErrorMessage code=0000 [Server error] message="java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: 'indexing_threads'  must be strictly positive">

but documentation says:
"indexing_threads: number of asynchronous indexing threads. ’0′ means synchronous indexing. Defaults to ’0′."

this was removed or i'm doing something wrong?

this is my query
CREATE CUSTOM INDEX testsort_lucene ON testsort (lucene)  USING 'org.apache.cassandra.db.index.stratio.RowIndex'  WITH OPTIONS = {      'refresh_seconds'    : '1',     'indexing_threads'   : '0',     'schema' : '{  default_analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer",  fields : {  counter1 : {type : "integer"},  value1 : {type: "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer"},  counter2 : {type : "integer"},  value2 : {type: "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer"},  counter3 : {type : "integer"},  value3 : {type: "text", analyzer : "org.apache.lucene.analysis.core.WhitespaceAnalyzer"}  }  }'  };

**Comment by kimsashenka** [comment]
i'm using Cassandra 2.1.2.1, 
com.datastax.driver.core.exceptions.InvalidQueryException: 'refresh_seconds' must be strictly positive

**Comment by adelapena** [comment]
Hi,

I guess the schema of the table to be indexed is something like this:
```
CREATE TABLE test.testsort (
    id int PRIMARY KEY,
    counter1 int,
    counter2 int,
    counter3 int,
    lucene text,
    value1 text,
    value2 text,
    value3 text
)
```
I  tried to reproduce the error with the following code:
```
Cluster cluster = Cluster.builder().addContactPoints("localhost").build();
Session session = cluster.connect();

session.execute("CREATE KEYSPACE test WITH replication = {'class':'SimpleStrategy', 'replication_factor': 1};");
session.execute("CREATE TABLE test.testsort (\n" +
                "\tid int PRIMARY KEY, \n" +
                "\tcounter1 int, \n" +
                "\tvalue1 text, \n" +
                "\tcounter2 int, \n" +
                "\tvalue2 text, \n" +
                "\tcounter3 int, \n" +
                "\tvalue3 text, \n" +
                "\tlucene text );");
session.execute("CREATE CUSTOM INDEX testsort_lucene ON test.testsort (lucene) \n" +
                "USING 'org.apache.cassandra.db.index.stratio.RowIndex' \n" +
                "WITH OPTIONS = { \n" +
                "\t'refresh_seconds' : '1', \n" +
                "\t'indexing_threads' : '0', \n" +
                "\t'schema' : '{ \n" +
                "\t\tdefault_analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\", \n" +
                "\t\tfields : { \n" +
                "\t\t\tcounter1 : {type : \"integer\"}, \n" +
                "\t\t\tvalue1 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\"}, \n" +
                "\t\t\tcounter2 : {type : \"integer\"}, \n" +
                "\t\t\tvalue2 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\"}, \n" +
                "\t\t\tcounter3 : {type : \"integer\"}, \n" +
                "\t\t\tvalue3 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\"} \n" +
                "\t\t}\n" +
                "\t}' \n" +
                "};");
session.close();
cluster.close();
```
I am running Stratio Cassandra 2.1.2.1 and my test program uses Java driver 2.1.2:
```
<dependency>
    <groupId>com.datastax.cassandra</groupId>
    <artifactId>cassandra-driver-core</artifactId>
    <version>2.1.2</version>
 </dependency>
```
The test runs fine, with no errors and with the expected behavior, so I don´t know how to reproduce the error. Could you please send me more data to reproduce the problem? Which version of the driver are you using? How is your keyspace/table schema?

**Comment by kimsashenka** [comment]
oh, sorry. everything works fine. guess i used earlier version of cassandra
