### ISSUE TITLE
Installation test failing 

### ISSUE THREAD

**Issue by jamesajones** [Stratio/stratio-cassandra#41]
The standard installation test are failing under the following conditions: OS Window 7 and Windows 10,
Dev Center 1.5.0, Our connection is to a single server (node). Created the namespace demo fine. When attempting to create the custom index is fails with the error that it cannot find com.statio.cassandra.lucene.Index which is present in the jar we created with maven and placed in the cassandra/lib directory.

**Comment by ealonsodb** [comment]
This project has been discontinued in favour of [cassandra-lucene-index](https://github.com/Stratio/cassandra-lucene-index). 

Please use that, and at least for now, it is not compatible at all with windows. 
Regards
