### ISSUE TITLE
Error create index

### ISSUE THREAD

**Issue by mplys** [Stratio/stratio-cassandra#42]
When I try to create index, I get error : `ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.NoClassDefFoundError: org/apache/cassandra/db/marshal/ByteType">`

Can anybody help me?

**Comment by adelapena** [comment]
@mplys, as answered #6 , this project has been discontinued in favour of [Cassandra Lucene Index](https://github.com/Stratio/cassandra-lucene-index), which maintains exactly the same features being a plugin of Apache Cassandra instead of a fork.
