### ISSUE TITLE
Comparison operators with strings using Lucene

### ISSUE THREAD

**Issue by SeenaLibin** [Stratio/stratio-cassandra#46]
Hi,
I have a column family which contains type text column page_load_time. I want to list all the entries whose page_load_time is less than 2 lakh. I have used the following query

select * from table_name where lucene='{filter:{type:"boolean",must:[{type : "range",field : "page_load_time", upper : "200000"}]}}';

which is returning wrong results due to type string of page_load_time.Is there any solution? Can you help me please?

**Comment by adelapena** [comment]
Hi @SeenaLibin,

Which version of both Apache Cassandra and the Lucene index plugin are you using? How is your table and index creation statement? Is `page_load_time` indexed as a `string`? If so, range filters would consider lexicographical order instead of numeric.

**Comment by SeenaLibin** [comment]
Hi,
My cassandra version is apache-cassandra-2.2.4 and lucene jar  is cassandra-lucene-index-plugin-2.2.4.3.jar

Lucene creating syntax is

CREATE CUSTOM INDEX index_name ON table_name (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds': '1', 'schema': '{ fields : created_at : {type : "string",sorted:true},page_load_time : {type : "string"}}} }'};

It is indexed as string

**Comment by adelapena** [comment]
Then you need an integer mapper:
```sql
CREATE CUSTOM INDEX index_name 
ON table_name (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
'refresh_seconds': '1', 
'schema': '{ 
    fields : {
      created_at : {type : "string", sorted: true},
      page_load_time : {type : "integer"}
    }
  }
'};
```
You can also use multiple mappers to `page_load_time`:
```sql
CREATE CUSTOM INDEX index_name 
ON table_name (lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
'refresh_seconds': '1', 
'schema': '{ 
    fields : {
      created_at : {type : "string", sorted: true},
      page_load_time_i : {column: "page_load_time", type : "integer"},
      page_load_time_s : {column: "page_load_time", type : "string"}
    }
  }
'};
```

**Comment by adelapena** [comment]
By the way, this project is a discontinued fork of Apache Cassandra, new issues related to the plugin  (cassandra-lucene-index-plugin) should be addressed to https://github.com/Stratio/cassandra-lucene-index

**Comment by SeenaLibin** [comment]
Thanks for your reply. It worked for me
