### ISSUE TITLE
wildcards with space

### ISSUE THREAD

**Issue by kimsashenka** [Stratio/stratio-cassandra#5]
when i try to search wildcards with space? i got nothing. when i use lucene directly i can store field untokenized, and perform wildcards with spaces. Can i do it here?

**Comment by adelapena** [comment]
Stratio index should have the same behavior as Lucene.  Can you please paste here the query, the index creation statement and the indexed data so that I can reproduce the issue?

**Comment by kimsashenka** [comment]
about indexing, tokenizing and wildcard

Wildcards are applied differently to tokenized fields and non-tokenized fields. Wildcards for tokenized fields match only words that were parsed from the value and not the entire value. For example, if you specify the search query msg:authentication*failed to search for the message The user authentication has failed on the server, it does not return the events with this message. This is because “*” does not match anything between “authentication” and “failed.” However, it matches any words that begin with “authentication” and end with “failed.” For example, it returns results if any of the following words are used: “authenticationhasfailed,” “authenticationuserfailed,” and “authenticationserverfailed.” For tokenized fields, all matching that uses wildcard searches is done on the words within the value and not on the full value.

**Comment by adelapena** [comment]
In the following example:
```
CREATE KEYSPACE IF NOT EXISTS test WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
USE test;

CREATE TABLE IF NOT EXISTS testwildcards(
	id int, 
	tokenized text, 
	nontokenized text, 
	lucene text,
PRIMARY KEY(id)) ;

CREATE CUSTOM INDEX  IF NOT EXISTS testwildcards_lucene ON testwildcards (lucene)  
USING 'com.stratio.cassandra.index.RowIndex'  
WITH OPTIONS = {                             
'refresh_seconds' : '0.1',     
'schema' : '{  
	fields : {
		id : {type : "integer"},  
		tokenized : {type: "text"},  
		nontokenized : {type: "string"}
		}  
	}'  
};
```
All these wildcard queries in the non-tokenized text return the existing rows:
```
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"nontokenized", value:"hello world"}}';
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"nontokenized", value:"hello?world"}}';
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"nontokenized", value:"he?lo*"}}';
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"nontokenized", value:"*wor?d"}}';
```
However, if we perform the same queries against the tokenized text:
```
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"tokenized", value:"hello world"}}';
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"tokenized", value:"hello?world"}}';
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"tokenized", value:"he?lo*"}}';
SELECT * FROM testwildcards  WHERE  lucene='{filter:{type:"wildcard", field:"tokenized", value:"*wor?d"}}';
```
Only the two last return the row. That is because the text "hello world" have been mapped to two tokens; "hello" and "world", and the two first wildacard queries are relative to a single token, exactly as the quoted text says.

I think that this is the expected behaviour. Do not you think so? Can you show me a more detailed example of the problem, if any?
