### ISSUE TITLE
Spatial search

### ISSUE THREAD

**Issue by albertocsm** [Stratio/stratio-cassandra#6]
I've seen spatial search has been worked on and it's already been merged onto develop. Whats the status?

**Comment by adelapena** [comment]
Hi Alberto,

Spatial search is still slightly immature. We have plans to add the functionality of Spatial Lucene as soon as possible.

At the moment, you can index points, rectangles and circles this way:

```
CREATE TABLE demo.users (
  name varchar,
  shape text,
  lucene text,
  PRIMARY KEY (name));

CREATE CUSTOM INDEX demo_lucene ON  demo.users (lucene) 
USING 'com.stratio.cassandra.index.RowIndex' WITH OPTIONS = {
'refresh_seconds':'1', 
 'schema':'{fields:{
    name:{type:"string"},
    shape:{type:"geo_shape"}
} }'};

INSERT INTO demo.users (name, shape) VALUES ( 'ID_0', '{type:"point", longitude:1, latitude:2}');
INSERT INTO demo.users (name, shape) VALUES ( 'ID_2', '{type:"point", longitude:2, latitude:2}');
INSERT INTO demo.users (name, shape) VALUES ( 'ID_1', '{type:"point", longitude:2, latitude:2}');
INSERT INTO demo.users (name, shape) VALUES ( 'ID_3', '{type:"point", longitude:3, latitude:3}');
INSERT INTO demo.users (name, shape) VALUES ( 'ID_4', '{type:"point", longitude:0, latitude:0}');
INSERT INTO demo.users (name, shape) VALUES ( 'ID_5', '{type:"rectangle", min_longitude:1, max_longitude:2, min_latitude:3, max_latitude:4}');
INSERT INTO demo.users (name, shape) VALUES ( 'ID_6', '{type:"circle", x:1, y:2, distance:"1km"}');
```

Note that actually shapes are represented by JSON text fields. We are considering extending Cassandra data types/marshallers for representing geometrical shapes.

You can query using Spatial Lucene relationships:
```
SELECT * FROM demo.users WHERE lucene='{filter:{type:"geo_shape", field:"shape", operator:"intersects", shape:{type:"rectangle", min_longitude:0, max_longitude:2, min_latitude:0, max_latitude:2}}}';
SELECT * FROM demo.users WHERE lucene='{filter:{type:"geo_shape", field:"shape", operator:"contains", shape:{type:"rectangle", min_longitude:0, max_longitude:2, min_latitude:0, max_latitude:2}}}';
SELECT * FROM demo.users WHERE lucene='{filter:{type:"geo_shape", field:"shape", operator:"is_disjoint_to", shape:{type:"rectangle", min_longitude:0, max_longitude:2, min_latitude:0, max_latitude:2}}}';
SELECT * FROM demo.users WHERE lucene='{filter:{type:"geo_shape", field:"shape", operator:"is_within", shape:{type:"rectangle", min_longitude:0, max_longitude:2, min_latitude:0, max_latitude:2}}}';
```

Also you can query using bounding boxes:
```
SELECT * FROM demo.users WHERE lucene='{filter:{type:"geo_bounding_box", field:"shape", min_longitude:0, max_longitude:1, min_latitude:0, max_latitude:2}}';
```

Distance filters are still inaccurate so we dot not recommend using them yet:
```
SELECT * FROM demo.users WHERE lucene='{filter:{type:"geo_distance", field:"shape", longitude:0, latitude:0, distance:"1km"}}';
```
We have also plans to add nearest-neighbor features.

We hope this will be useful and of course we welcome any suggestions.

**Comment by albertocsm** [comment]
Great! I'll give it a spin.

**Comment by jsebrien** [comment]
Are there any improvements regarding Distance filters ?

Julien

**Comment by adelapena** [comment]
Yes, there are. This project has been discontinued in favour of [Cassandra Lucene Index](https://github.com/Stratio/cassandra-lucene-index), which maintains exactly the same features being a plugin of Apache Cassandra instead of a fork. The last version of the plugin includes basic [distance filtering](https://github.com/Stratio/cassandra-lucene-index/blob/branch-2.1.7/doc/src/site/sphinx/documentation.rst#geo-distance-query).

**Comment by jsebrien** [comment]
Ok, this is great.
You mean that it is better to download standard cassandra release, and manually integrate Cassandra Lucene Index plugin (instead of using stratio cassandra fork)?

**Comment by adelapena** [comment]
Yes, it is better to use the Apache Cassandra release (2.1.7) with the plugin. It is as simple as copying the plugin's JAR into the Cassandra's lib folder. There is also a Maven target to automatically perform the patching:

```
mvn clean package -Pdownload_and_patch -Dcassandra_home=<CASSANDRA_HOME>
```

In addition, let me inform you that the fork is not maintained anymore.

**Comment by jsebrien** [comment]
Ok, thanks a lot!

**Comment by albertocsm** [comment]
Great news.

**Comment by srinivasanviki** [comment]
with     https://github.com/Stratio/cassandra-lucene-index  
Iam facing this error while creating lucene index

java.lang.NoClassDefFoundError: org/apache/cassandra/db/marshal/ByteType

**Comment by mplys** [comment]
Hi srinivasanviki, do you solved your issue? I have same problem:
ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.NoClassDefFoundError: org/apache/cassandra/db/marshal/ByteType">

**Comment by mplys** [comment]
java.lang.NoClassDefFoundError: org/apache/cassandra/db/marshal/ByteType
