### ISSUE TITLE
data inserted during update is not indexed

### ISSUE THREAD

**Issue by kimsashenka** [Stratio/stratio-cassandra#7]
When insert data with UPDATE, it is not indexed.
Sample program to reproduce
===================================================================
package arta.synergy.common.docs;
    
    import com.datastax.driver.core.*;
    
    /**
     * Created by exile
     * Date: 27.11.14
     * Time: 10:36
     */
    public class CassandraUpsertTest {
        public static void main(String[] args) {
            final CassandraUpsertTest ct = new CassandraUpsertTest();
            Session session = null;
            try {
    
                ct.connect("127.0.0.1");
                session = ct.getSession();
    
    
                session.execute("CREATE TABLE testsort(id int, counter1 int, value1 text, lucene text, " +
                        " PRIMARY KEY(id, counter1)) ");
    
                session.execute("CREATE CUSTOM INDEX testsort_lucene ON testsort (lucene) " +
                        " USING 'org.apache.cassandra.db.index.stratio.RowIndex' " +
                        " WITH OPTIONS = {     " +
                        " 'refresh_seconds'    : '1',    " +
                        " 'indexing_threads'   : '0',    " +
                        " 'indexing_queues_size' : '10', " +
                        " 'schema' : '{ " +
                        " default_analyzer : \"org.apache.lucene.analysis.core.WhitespaceAnalyzer\", " +
                        " fields : { " +
                        " counter1 : {type : \"integer\"}, " +
                        " value1 : {type: \"text\", analyzer : \"org.apache.lucene.analysis.ru.RussianAnalyzer\"} " +
                        " } " +
                        " }' " +
                        " };\n");
    
    
                final String[] str = new String[]{"1", "1", "1", "1", "1 док", "1 докум", "11", "111", "1 документ в посике", "11 док",  "11 докум",  "111 докум",
                        "слова наши - просто слова", "слова поэта", "слова", "словари словари",
                        "словари", "словари словарный", "словарный", "словарный словарный словарный словарный словарный"};
                for(int i=0; i<str.length; i++){
                    ct.getSession().execute("UPDATE testsort SET VALUE1='"+str[i]+"' WHERE id=1 AND counter1="+i+" ");
                }
    
                Thread.sleep(1000);
    
                System.out.println("table data =====================================================");
    
                ResultSet res=session.execute("SELECT * FROM testsort");
                while(!res.isExhausted()){
                    Row r = res.one();
                    System.out.println(r.getInt("id")+"  "+r.getString("value1")+"  "+r.getString("lucene"));
                }
    
    
                System.out.println("table data with sorting =====================================================");
                SimpleStatement st = new SimpleStatement("SELECT id, counter1, value1,  lucene " +
                        " FROM testsort " +
                        " WHERE " +
                        " lucene= '{" +
                        "sort : {   fields :[  { field : \"value1\" , reverse : true } ]  }" +
                        "" +
                        "}'"
                );
                res=session.execute(st);
                while(!res.isExhausted()){
                    Row r = res.one();
                    System.out.println(r.getInt("id")+"  "+r.getString("value1")+"  "+r.getString("lucene"));
                }
    
            } catch (Exception e) {
                e.printStackTrace();
            }finally {
                if(session != null ) {
                    session.execute("drop table testsort");
                    session.close();
                }
                ct.close();
            }
    
        }
    
        private Cluster cluster;
        private Session session;
    
    
        public void connect(String node) {
            cluster = Cluster.builder()
                    .addContactPoint(node)
                    .withCredentials("cassandra", "cassandra").build();
            Metadata metadata = cluster.getMetadata();
            System.out.printf("Connected to cluster: %s\n",
                    metadata.getClusterName());
            for ( Host host : metadata.getAllHosts() ) {
                System.out.printf("Datacenter: %s; Host: %s; Rack: %s\n",
                        host.getDatacenter(), host.getAddress(), host.getRack());
            }
    
            this.session = cluster.connect("synergy");
            System.out.println("session got");
        }
    
    
        public Session getSession(){
            return this.session;
        }
    
        public void close(){
            cluster.close();
        }
    }

**Comment by kimsashenka** [comment]
Program result
=======================================================
Connected to cluster: Test Cluster
Datacenter: datacenter1; Host: /127.0.0.1; Rack: rack1
session got
table data =====================================================
1  1  null
1  1  null
1  1  null
1  1  null
1  1 док  null
1  1 докум  null
1  11  null
1  111  null
1  1 документ в посике  null
1  11 док  null
1  11 докум  null
1  111 докум  null
1  слова наши - просто слова  null
1  слова поэта  null
1  слова  null
1  словари словари  null
1  словари  null
1  словари словарный  null
1  словарный  null
1  словарный словарный словарный словарный словарный  null
table data with sorting =====================================================

**Comment by adelapena** [comment]
You are right, there is a bug related to clustering keys. I have just fixed it in develop branch. Thanks!
