### ISSUE TITLE
Windows instalation

### ISSUE THREAD

**Issue by razvanz** [Stratio/stratio-cassandra#8]
I wouldn't normally address this here, but in a mail or other contact method.

I have replaced the Apache Cassandra with your extended version. Previously, I had the Apache `2.1.0` version installed and running on a Win Server 2012, but I cannot run your latest release `2.1.2.2`.

I'm getting the error: `Could not find or load main class org.apache.cassandra.service.CassandraDaemon`

Could you provide a guide for installing it on windows?

**Comment by adelapena** [comment]
I have tested with a manual installation on Windows 2008 with no problems, just compile and run. Oracle JDK and Ant are required for compiling, and Python 2.7 for cqlsh. However, Windows is not recommended for production usage.
The DataStax MSI installer is not provided because, as far as I know, it is not open source. How do you have installed it?

**Comment by razvanz** [comment]
I just got the latest release, changed the configuration and ran cassandra.bat without compiling  anything. I will try to compile and run it again.

**Comment by razvanz** [comment]
I've got it running.

**Steps**:

1. Download `stratio-cassandra`
2. Download `ant`
3. Download `Java` (JDK or SDK is required for building)
4. Set environment variables (`JAVA_HOME`, `CASSANDRA_HOME`, `ANT_HOME`)
5. Build `stratio-cassandra` with `ant`
6. Change folder paths in `cassandra.yaml`according to Windows file paths (`data`, `commitlog`, `saved_caches` paths)
7. Run `cassandra.bat`

**Comment by razvanz** [comment]
PS:   I wasn't able to create a `keyspace` with JAVA 8. After rolling back to the latest JAVA 7 it worked.

**Comment by eric-aldinger** [comment]
I am reviewing Cassandra based platforms. I am unable to find updated documentation around Stratio cross platform support. I normally assume this means Linux only platform support. I am excited about Stratio so I wanted to verify. Is there a production ready version of Stratio Cassandra for Windows? The 1.6 compatibility matrix omits OS support. 
https://docs.google.com/spreadsheets/d/1dzdm1DVaZ-0B0g_yrkFVgLgZ3rHprmSyHWqpmnjgU2Q/edit#gid=1878106919
